Modify pre-commit, install.sh, and trapdoor.cfg
Allow commits even when there are untracked files
Allow commits with print statements
Disable .gitignore and cleanfiles.sh in install.sh
Create qaworkdir and copy over trapdoor.cfg and pycodestyle.ini in install.sh
Remove qa directory when testing python code

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -21,17 +21,17 @@ if [[ `git diff --cached --check` ]]; then
     exit 1
 fi
 
-# Check for untracked files (not in .gitignore)
-if [[ `git status -u ${CODE_DIRS} -s | grep "^??"` ]]; then
-    echo -e "${red}Commit failed: untracked files (not in .gitignore).${color_end}"
-    git status -u ${CODE_DIRS} -s | grep "^??"
-    exit 1
-fi
+## Check for untracked files (not in .gitignore)
+#if [[ `git status -u ${CODE_DIRS} -s | grep "^??"` ]]; then
+#    echo -e "${red}Commit failed: untracked files (not in .gitignore).${color_end}"
+#    git status -u ${CODE_DIRS} -s | grep "^??"
+#    exit 1
+#fi
 
-# Check for new print statements
-if [[ `git diff --cached | grep '^+' | sed  's/^.//' | sed 's:#.*$::g' | grep 'print '` ]]; then
-    echo -e "${red}Commit failed: print statements${color_end}"
-    git diff --cached | grep '^+' | sed  's/^.//' | sed 's:#.*$::g' | grep print
-    exit 1
-fi
+## Check for new print statements
+#if [[ `git diff --cached | grep '^+' | sed  's/^.//' | sed 's:#.*$::g' | grep 'print '` ]]; then
+#    echo -e "${red}Commit failed: print statements${color_end}"
+#    git diff --cached | grep '^+' | sed  's/^.//' | sed 's:#.*$::g' | grep print
+#    exit 1
+#fi
 
