Update cleanfiles.sh, install.sh, and pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -7,7 +7,7 @@
 
 # Change this to a space-delimited list of dirs in the top level of your project that contain
 # code to be checked.
-CODE_DIRS="data horton doc scripts tools"
+CODE_DIRS="data wfns doc scripts tools"
 
 ## Nothing to change below this line ##
 
@@ -21,12 +21,12 @@ if [[ `git diff --cached --check` ]]; then
     exit 1
 fi
 
-# Check for untracked files (not in .gitignore)
-if [[ `git status -u ${CODE_DIRS} -s | grep "^??"` ]]; then
-    echo -e "${red}Commit failed: untracked files (not in .gitignore).${color_end}"
-    git status -u ${CODE_DIRS} -s | grep "^??"
-    exit 1
-fi
+# # Check for untracked files (not in .gitignore)
+# if [[ `git status -u ${CODE_DIRS} -s | grep "^??"` ]]; then
+#     echo -e "${red}Commit failed: untracked files (not in .gitignore).${color_end}"
+#     git status -u ${CODE_DIRS} -s | grep "^??"
+#     exit 1
+# fi
 
 # Check for new print statements
 if [[ `git diff --cached | grep '^+' | sed  's/^.//' | sed 's:#.*$::g' | grep 'print '` ]]; then
